---

- hosts: test
  gather_facts: false
  tasks:
    - ping:

    - name: create dir
      file:
          path: "{{rootDir}}/{{projDir}}"
          state: directory
          mode: 0755
          
    - name: copy file
      copy:
          src: "{{rootDir}}/{{projDir}}"
          dest: "{{rootDir}}"
          
    - name: install node.js
      unarchive: 
          src: "{{rootDir}}/{{projDir}}/{{nodeVer}}.tar.gz" 
          dest: "{{rootDir}}/{{projDir}}"
      
    - name: "Install forever"
      npm: 
          name: forever 
          global: yes 
          state: present

    - name: "Check list of Node.js apps running."
      command: forever list
      register: forever_list
      changed_when: false

    - name: "Run node.js"
      command: "forever -c {{rootDir}}/{{projDir}}/{{nodeVer}}/bin/node start {{rootDir}}/{{projDir}}/server.js"
      
